title: Canon.com/ijsetup | Wireless & USB  Setup | Ij Canon Printer Driver
description: Canon.com/ijsetup - Click on the Get started button to download the printer driver from the website Canon.com/ijsetup.
